version: '3.7'

services:
  regression:
    image: python:3.9.13-alpine3.16
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      - BASE_URL=${BASE_URL}
      - API_BASE_URL=${API_BASE_URL}
      - X_NODE_ID=${X_NODE_ID}
      - LOGIN_PLAYER=${LOGIN_PLAYER}
      - PASSWORD_PLAYER=${PASSWORD_PLAYER}
      - LOGIN_ADMIN=${LOGIN_ADMIN}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}