name: UI/API Tests of CHAT

on: workflow_dispatch

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Install Python dependencies
        run: |
          docker build -t myimage .
          docker run myimage pip install -r requirements.txt
          docker run myimage pip list

      - name: Run UI-tests via docker-compose
        env:
          BASE_URL: ${{ secrets.BASE_URL }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}
          X_NODE_ID: ${{ secrets.X_NODE_ID }}
          LOGIN_PLAYER: ${{ secrets.LOGIN_PLAYER }}
          PASSWORD_PLAYER: ${{ secrets.PASSWORD_PLAYER }}
          LOGIN_ADMIN: ${{ secrets.LOGIN_ADMIN }}
          PASSWORD_ADMIN: ${{ secrets.PASSWORD_ADMIN }}
        run: |
          docker-compose up --exit-code-from regression || true

      - name: Print environment variables
        run: |
          echo "BASE_URL: $BASE_URL"
          echo "API_BASE_URL: $API_BASE_URL"
          echo "X_NODE_ID: $X_NODE_ID"
          echo "LOGIN_PLAYER: $LOGIN_PLAYER"
          echo "PASSWORD_PLAYER: $PASSWORD_PLAYER"
          echo "LOGIN_ADMIN: $LOGIN_ADMIN"
          echo "PASSWORD_ADMIN: $PASSWORD_ADMIN"

      - name: Copy history from gh-pages to allure-results
        run: |
          if [ -d "./.github/gh-pages/history" ]; then
            mkdir -p allure-results/history 
            cp -R ./.github/gh-pages/history/* allure-results/history/
          else
            echo "Directory ./.github/gh-pages/history does not exist. Skipping copying."
          fi

      - name: Generate Allure report
        run: |
          docker-compose run regression /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          if [ ! -d "./.github/gh-pages/history" ]; then
            mkdir -p ./.github/gh-pages/history
          fi
          cp -R allure-report/history/* ./.github/gh-pages/history/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
          

